### ISSUE TITLE
[help] what am I doing wrong?

### ISSUE THREAD

**Issue by Tsyklop** [korti11/JsonForge#2]
I did a test mode. But when you start crash.

Archives since I do.

https://drive.google.com/file/d/0B9c2x-D6eUzecnN4YVJlbGxHN1k/view?usp=sharing

Error: http://pastebin.com/LCnZLh5C

**Comment by korti11** [comment]
God dammit. I use a library for read the json files and the library won't compile with it as I hoped. So I have to use the gson library that comes with forge. I hope I can fixe the bug tomorrow and upload the new version.

**Comment by Tsyklop** [comment]
Okay!

**Comment by korti11** [comment]
Bug is fixed. New version is on the curse page.
