### ISSUE TITLE
and again the crash ...

### ISSUE THREAD

**Issue by Tsyklop** [korti11/JsonForge#3]
What's wrong this time?

http://pastebin.com/5J96m8w0

My test mod here: https://drive.google.com/file/d/0B9c2x-D6eUzecnN4YVJlbGxHN1k/view?usp=sharing

Please make an example of such a mod as it should be, and lay on the wiki. It is not clear what to do.

**Comment by korti11** [comment]
I fixed the bug and tested the new version, now it should work. I also have add a download link on the main wiki page to a example mod.
